# -*- coding: utf-8 -*-
"""docsToNotes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19OhM1ILeUQS0dGS8_iNNLuti9X8CkjQi
"""

!pip install sentence-transformers

!pip install PyMuPDF

import fitz
from google.colab import drive
drive.mount('/content/gdrive')

import spacy
filename = "/content/gdrive/My Drive/Colab Notebooks/PDFfiles/file1.pdf"
doc = fitz.open(filename) 
page = doc.load_page(0)
text = page.get_text()

from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
model_name = 'bert-base-nli-mean-tokens'
model = SentenceTransformer(model_name)

from __future__ import unicode_literals, print_function
from spacy.lang.en import English 
nlp = English()
nlp.add_pipe(nlp.create_pipe('sentencizer')) # updated
doc = nlp(text)
sentences = [sent.string.strip() for sent in doc.sents]
sentence_vecs = model.encode(sentences)
singleTimeSentence = []
index = 0

for s in sentences:
  single_vecs = model.encode(singleTimeSentence)
  if index == 0 or index == 1:
    singleTimeSentence.append(s)    
  else:
    similarityVal = cosine_similarity([sentence_vecs[index]], single_vecs[0:])
    valDiff = str(similarityVal[0])
    valDiff = valDiff.replace('[', '')
    valDiff = valDiff.replace(']', '')
    valDiffs = valDiff.split()
    repeat = False
    for x in valDiffs:
      if(float(x) > 0.70):
        repeat = True
        break
    if not repeat:
      singleTimeSentence.append(s) 
  index+=1

noteWriting = []
linebyline = []
for notes in singleTimeSentence:
  individualLines = notes.split('\n')
  for n in individualLines:
    noteWriting.append(n)

hyphen = False
addition = ''
index = 0
for x in noteWriting:
  if(x[0].isupper()):
    if(not addition == ''):
      linebyline.append(addition)
      addition = ''
  
    if(x[-1] == "-"):
      addition = addition + x.replace('-', '')
      hyphen = True
    else:
      addition = addition + x

  else:
    if(x[-1] == "-"):
      if(not hyphen):
        addition = addition + " "
      addition = addition + x.replace('-', '')
    else:
      if(not hyphen):
        addition = addition + " "
      addition = addition + x
  if (index == len(noteWriting)-1):
    linebyline.append(addition)
  index+=1

!pip install python-docx
from docx import Document
from docx.shared import Inches

document = Document()
document.add_heading(linebyline[0], 0)
index = 0
for lines in linebyline:
  if index == 0:
    document.add_paragraph("")
  elif lines[-1] == ".":
    p = document.add_paragraph(lines)
  else:
    document.add_heading(lines, level=2)
  index+=1

document.add_page_break()
document.save('/content/gdrive/My Drive/Colab Notebooks/PDFfiles/file1.docx')